#!/bin/bash

build() {
    # for debugging
    add_module "tpm_tis"
    add_binary "/usr/lib/tpmkey"
    add_binary "/usr/bin/ltrace"
    add_systemd_unit "tpmkey.service"
    add_systemd_unit "cryptsetup-pre.target"
    add_systemd_unit "cryptsetup.target"

    add_symlink "/usr/lib/systemd/system/sysinit.target.wants/cryptsetup-pre.target" "/usr/lib/systemd/system/cryptsetup-pre.target"
    add_symlink "/usr/lib/systemd/system/cryptsetup-pre.target.wants/tpmkey.service" "/usr/lib/systemd/system/tpmkey.service"

    add_udev_rule "70-tpmd.rules"

    # avoid udev warnings
    cat >> "$BUILDROOT/etc/group" <<EOF
tty:x:5:
disk:x:6:
lp:x:7:
kmem:x:9:
uucp:x:14:
kvm:x:78:
video:x:91:
audio:x:92:
optical:x:93:
storage:x:95:
input:x:97:
render:x:986:
EOF
}
